apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  virtualhost.conf: |
    server {
      listen 8080;
      server_name {{ .Values.traefik.iosdk }};
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location /api/ {
          proxy_pass http://openwhisk-nginx/api/v1/web/guest/;
                }
      location / {
          root /opt/io-sdk/admin/web/public/;
          index index.html;
                }
        }

