apiVersion: v1
kind: Service
metadata:
  labels:
    app: iosdk-nginx
  name: iosdk-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: iosdk-nginx

