apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: iosdk-redis
    component: cache
  name: iosdk-redis
  namespace: {{ .Values.openwhisk.namespace }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iosdk-redis
  template:
    metadata:
      labels:
        name: iosdk-redis
        component: cache
    spec:
      containers:
      - name: iosdk-redis
        image: redis
        imagePullPolicy: Always
        args: ["--requirepass", "$(__NIM_REDIS_PASSWORD)"]
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: MASTER
          value: "true"
        - name: __NIM_REDIS_PASSWORD
          value: "iosdk-password"
