apiVersion: v1
kind: Service
metadata:
  labels:
    component: cache
    name: redis
    manager: kubectl
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
