apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.traefik.admin }}`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  namespace: {{ .Values.openwhisk.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.traefik.api }}`)
    kind: Rule
    services:
    - name: owdev-nginx
      namespace: openwhisk
      port: 80
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: iosdk
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.traefik.iosdk }}`)
    kind: Rule
    services:
    - name: iosdk-svc
      namespace: {{ .Release.Namespace }}   
      port: 80
  tls:
    certResolver: default
