apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
spec:
  entryPoints:
    - websecure
  routes:
 #- match: (Host(`traefik.noiopen.it`) && PathPrefix(`/tls`)) || Host(`www.noiopen.it`)
  - match: Host(`traefik.noiopen.it`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api.noiopen.it`)
    kind: Rule
    services:
    - name: owdev-nginx
      namespace: openwhisk
      port: 80
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: iosdk
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`iosdk.noiopen.it`)
    kind: Rule
    services:
    - name: iosdk-svc
      namespace: default
      port: 80
  tls:
    certResolver: default
