apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  virtualhost.conf: |
    server {
      listen 8080;
      server_name iosdk.noiopen.it;
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location /api/ {
          proxy_pass http://10.111.90.7/api/;
                }
      location / {
          root /opt/io-sdk/admin/web/public/;
          index index.html;
                }
        }

